/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zakats;

import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import static zakats.Muzaki.IdAdminMuzaki;

/**
 *
 * @author FARHAN
 */
public class SuperAdmin extends javax.swing.JFrame {

    /**
     * Creates new form SuperAdmin
     */
    public SuperAdmin() {
        batas = 20;
        initComponents();
        showLogLogin(logLogin, 0);
        showLogMustahik(logMustahik, 0);
        showLogMuzaki(logMuzaki, 0);
        showLogItem(logItem, 0);
        dataAdmin();
        pagilogin();
        pagimustahik();
        pagimuzaki();
        pagiitem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    ResultSet Rs = null;
    Connection Con = null;
    Statement St = null;

    int batas;
    int xMouse,yMouse;

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Admin = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        namaAdminIndex = new javax.swing.JTextField();
        roleAdmin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logLogin = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        logMustahik = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        logMuzaki = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        logItem = new javax.swing.JTable();
        printDataExcelLogLoginAdmin = new javax.swing.JButton();
        printDataExcel1Mustahik = new javax.swing.JButton();
        printDataExcel2Item = new javax.swing.JButton();
        printDataExcel3Mustahik = new javax.swing.JButton();
        paginasiBoxlogin = new javax.swing.JComboBox<>();
        paginasiBox1mustahik = new javax.swing.JComboBox<>();
        paginasiBox2item = new javax.swing.JComboBox<>();
        paginasiBox3muzaki = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(116, 202, 138));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\FARHAN\\Documents\\Tugas dan materi Kuliah UPN\\Semester 4\\PBO\\Gambar Asset\\new admin\\cctv-camera.png")); // NOI18N
        jLabel1.setText("Aktivitas");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        Admin.setBackground(new java.awt.Color(255, 255, 255));
        Admin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Admin.setForeground(new java.awt.Color(255, 255, 255));
        Admin.setIcon(new javax.swing.ImageIcon("C:\\Users\\FARHAN\\Documents\\Tugas dan materi Kuliah UPN\\Semester 4\\PBO\\Gambar Asset\\new admin\\add-user.png")); // NOI18N
        Admin.setText("Admin");
        Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminMouseClicked(evt);
            }
        });

        logout.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setIcon(new javax.swing.ImageIcon("C:\\Users\\FARHAN\\Documents\\Tugas dan materi Kuliah UPN\\Semester 4\\PBO\\Gambar Asset\\user\\logout.png")); // NOI18N
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Menu");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\FARHAN\\Documents\\Tugas dan materi Kuliah UPN\\Semester 4\\PBO\\Gambar Asset\\new admin\\return.png")); // NOI18N
        jLabel6.setText("Kembali");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Admin)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 680, Short.MAX_VALUE)
                .addComponent(logout)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        namaAdminIndex.setEditable(false);
        namaAdminIndex.setBackground(new java.awt.Color(255, 255, 255));
        namaAdminIndex.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        namaAdminIndex.setForeground(new java.awt.Color(116, 202, 138));
        namaAdminIndex.setBorder(null);

        roleAdmin.setEditable(false);
        roleAdmin.setBackground(new java.awt.Color(255, 255, 255));
        roleAdmin.setForeground(new java.awt.Color(255, 255, 255));
        roleAdmin.setBorder(null);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\FARHAN\\Documents\\Tugas dan materi Kuliah UPN\\Semester 4\\PBO\\Gambar Asset\\flaticon\\minimize.png")); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(namaAdminIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roleAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 587, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(402, 402, 402))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaAdminIndex, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(roleAdmin)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel3.setBackground(new java.awt.Color(116, 202, 138));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(116, 202, 138));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Log Aktivitas");

        logLogin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "ID Admin", "Username", "Nama Admin", "Waktu"
            }
        ));
        jScrollPane1.setViewportView(logLogin);

        jLabel4.setBackground(new java.awt.Color(116, 202, 138));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(116, 202, 138));
        jLabel4.setText("Log Login Admin");

        jLabel5.setBackground(new java.awt.Color(116, 202, 138));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(116, 202, 138));
        jLabel5.setText("Log Aktivitas Admin di Mustahik");

        logMustahik.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane2.setViewportView(logMustahik);

        jLabel8.setBackground(new java.awt.Color(116, 202, 138));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(116, 202, 138));
        jLabel8.setText("Log Aktivitas Admin di Muzaki");

        logMuzaki.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane3.setViewportView(logMuzaki);

        jLabel9.setBackground(new java.awt.Color(116, 202, 138));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(116, 202, 138));
        jLabel9.setText("Log Aktivitas Admin di Item");

        logItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane4.setViewportView(logItem);

        printDataExcelLogLoginAdmin.setBackground(new java.awt.Color(51, 102, 255));
        printDataExcelLogLoginAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        printDataExcelLogLoginAdmin.setForeground(new java.awt.Color(255, 255, 255));
        printDataExcelLogLoginAdmin.setText("Print Excel");
        printDataExcelLogLoginAdmin.setBorderPainted(false);
        printDataExcelLogLoginAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printDataExcelLogLoginAdminActionPerformed(evt);
            }
        });

        printDataExcel1Mustahik.setBackground(new java.awt.Color(51, 102, 255));
        printDataExcel1Mustahik.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        printDataExcel1Mustahik.setForeground(new java.awt.Color(255, 255, 255));
        printDataExcel1Mustahik.setText("Print Excel");
        printDataExcel1Mustahik.setBorderPainted(false);
        printDataExcel1Mustahik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printDataExcel1MustahikActionPerformed(evt);
            }
        });

        printDataExcel2Item.setBackground(new java.awt.Color(51, 102, 255));
        printDataExcel2Item.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        printDataExcel2Item.setForeground(new java.awt.Color(255, 255, 255));
        printDataExcel2Item.setText("Print Excel");
        printDataExcel2Item.setBorderPainted(false);
        printDataExcel2Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printDataExcel2ItemActionPerformed(evt);
            }
        });

        printDataExcel3Mustahik.setBackground(new java.awt.Color(51, 102, 255));
        printDataExcel3Mustahik.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        printDataExcel3Mustahik.setForeground(new java.awt.Color(255, 255, 255));
        printDataExcel3Mustahik.setText("Print Excel");
        printDataExcel3Mustahik.setBorderPainted(false);
        printDataExcel3Mustahik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printDataExcel3MustahikActionPerformed(evt);
            }
        });

        paginasiBoxlogin.setBackground(new java.awt.Color(0, 102, 204));
        paginasiBoxlogin.setForeground(new java.awt.Color(255, 255, 255));
        paginasiBoxlogin.setAutoscrolls(true);
        paginasiBoxlogin.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                paginasiBoxloginItemStateChanged(evt);
            }
        });
        paginasiBoxlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paginasiBoxloginActionPerformed(evt);
            }
        });

        paginasiBox1mustahik.setBackground(new java.awt.Color(0, 102, 204));
        paginasiBox1mustahik.setForeground(new java.awt.Color(255, 255, 255));
        paginasiBox1mustahik.setAutoscrolls(true);
        paginasiBox1mustahik.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                paginasiBox1mustahikItemStateChanged(evt);
            }
        });
        paginasiBox1mustahik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paginasiBox1mustahikActionPerformed(evt);
            }
        });

        paginasiBox2item.setBackground(new java.awt.Color(0, 102, 204));
        paginasiBox2item.setForeground(new java.awt.Color(255, 255, 255));
        paginasiBox2item.setAutoscrolls(true);
        paginasiBox2item.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                paginasiBox2itemItemStateChanged(evt);
            }
        });
        paginasiBox2item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paginasiBox2itemActionPerformed(evt);
            }
        });

        paginasiBox3muzaki.setBackground(new java.awt.Color(0, 102, 204));
        paginasiBox3muzaki.setForeground(new java.awt.Color(255, 255, 255));
        paginasiBox3muzaki.setAutoscrolls(true);
        paginasiBox3muzaki.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                paginasiBox3muzakiItemStateChanged(evt);
            }
        });
        paginasiBox3muzaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paginasiBox3muzakiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(paginasiBox3muzaki, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(printDataExcel1Mustahik, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(paginasiBoxlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(printDataExcelLogLoginAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(614, 614, 614))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))))
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(620, 620, 620)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(paginasiBox1mustahik, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(printDataExcel3Mustahik, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(paginasiBox2item, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(printDataExcel2Item, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(printDataExcelLogLoginAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(printDataExcel1Mustahik, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(paginasiBox3muzaki, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(paginasiBoxlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(paginasiBox1mustahik, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(printDataExcel3Mustahik, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(printDataExcel2Item, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(paginasiBox2item, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void dataAdmin() {
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbzakat", "root", "");
            St = Con.createStatement();
            Rs = St.executeQuery("SELECT * FROM admin WHERE id_admin = '" + IdAdminMuzaki.getText() + "'");
            if (Rs.next()) {
                namaAdminIndex.setText("Nama Admin : " + Rs.getString(2));
                roleAdmin.setText(Rs.getString(5));
            } else {
                JOptionPane.showMessageDialog(this, "Kamu belum login");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    public void openFile(String file) {
        try {
            File path = new File(file);
            Desktop.getDesktop().open(path);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e + "bagian openFIle");
        }
    }

    public void exportExcel(JTable jk) {
        try {
            JFileChooser JFileChooser = new JFileChooser();
            JFileChooser.showSaveDialog(jk);
            File saveFile = JFileChooser.getSelectedFile();
            if (saveFile != null) {
                saveFile = new File(saveFile.toString() + ".xlsx");
                Workbook wb = new XSSFWorkbook();
                Sheet sheet = wb.createSheet("Mustahik");

                Row rowcol = sheet.createRow(0);
                for (int i = 0; i < jk.getColumnCount(); i++) {
                    Cell cell = rowcol.createCell(i);
                    cell.setCellValue(jk.getColumnName(i));
                }

                for (int j = 0; j < jk.getRowCount(); j++) {
                    Row row = sheet.createRow(j + 1);
                    for (int k = 0; k < jk.getColumnCount(); k++) {
                        Cell cell = row.createCell(k);
                        if (jk.getValueAt(j, k) != null) {
                            cell.setCellValue(jk.getValueAt(j, k).toString());
                        }
                    }
                }

                FileOutputStream out = new FileOutputStream(new File(saveFile.toString()));
                wb.write(out);
                wb.close();
                out.close();
                openFile(saveFile.toString());
            } else {
                JOptionPane.showMessageDialog(this, "Error Dalam Export Excell");
            }

        } catch (FileNotFoundException e) {
            System.out.println(e);
        } catch (IOException io) {
            System.out.println(io);
        }
    }

    private void pagilogin() {
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbzakat", "root", "");
            St = Con.createStatement();
            Rs = St.executeQuery("SELECT * FROM logging");
            Rs.last();
            int jumlah = (int) Math.ceil((Rs.getRow()) / batas) + 1;
            int no = 1;
            paginasiBoxlogin.removeAllItems();
            while (no <= jumlah) {
                paginasiBoxlogin.addItem(Integer.toString(no));
                no++;
            }
        } catch (Exception e) {
        }
    }

    private void showLogLogin(JTable jt, int posisi) {
        DefaultTableModel model = new DefaultTableModel(new String[]{
            "No Login", "ID Admin", "Username", "Nama Admin", "Waktu Log"
        }, 0);
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbzakat", "root", "");
            St = Con.createStatement();
            Rs = St.executeQuery("SELECT * FROM logging LIMIT " + posisi + "," + batas);
            while (Rs.next()) {
                int No = Rs.getInt("No");
                int id_admin = Rs.getInt("id_admin");
                String username = Rs.getString("username");
                String nama_admin = Rs.getString("nama_admin");
                String waktu_log = Rs.getString("waktu_log");
                model.addRow(new Object[]{
                    No, id_admin, username, nama_admin, waktu_log
                });
            }
            jt.setModel(model);

        } catch (Exception e) {
        }
    }

//        logMustahik
    private void pagimustahik() {
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbzakat", "root", "");
            St = Con.createStatement();
            Rs = St.executeQuery("SELECT * FROM log_mustahik");
            Rs.last();
            int jumlah = (int) Math.ceil((Rs.getRow()) / batas) + 1;
            int no = 1;
            paginasiBox1mustahik.removeAllItems();
            while (no <= jumlah) {
                paginasiBox1mustahik.addItem(Integer.toString(no));
                no++;
            }
        } catch (Exception e) {
        }
    }

    private void showLogMustahik(JTable jt, int posisi) {
        DefaultTableModel model = new DefaultTableModel(new String[]{
            "No Log Mustahik", "ID Admin", "ID Mustahik", "Aksi", "Waktu Log"
        }, 0);
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbzakat", "root", "");
            St = Con.createStatement();
            Rs = St.executeQuery("SELECT * FROM log_mustahik LIMIT " + posisi + "," + batas);
//             logMustahik.setModel(DbUtils.resultSetToTableModel(Rs));
            while (Rs.next()) {
                int id_log_mustahik = Rs.getInt("id_log_mustahik");
                int id_admin = Rs.getInt("id_admin");
                int id_mustahik = Rs.getInt("id_mustahik");
                String aksi = Rs.getString("aksi");
                String waktu = Rs.getString("waktu");
                model.addRow(new Object[]{
                    id_log_mustahik, id_admin, id_mustahik, aksi, waktu
                });
            }
            jt.setModel(model);

        } catch (Exception e) {
        }
    }

    private void pagimuzaki() {
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbzakat", "root", "");
            St = Con.createStatement();
            Rs = St.executeQuery("SELECT * FROM log_muzaki");
            Rs.last();
            int jumlah = (int) Math.ceil((Rs.getRow()) / batas) + 1;
            int no = 1;
            paginasiBox3muzaki.removeAllItems();
            while (no <= jumlah) {
                paginasiBox3muzaki.addItem(Integer.toString(no));
                no++;
            }
        } catch (Exception e) {
        }
    }

    private void showLogMuzaki(JTable jt, int posisi) {
        DefaultTableModel model = new DefaultTableModel(new String[]{
            "No Log Muzaki", "ID Admin", "ID Mustahik", "Aksi", "Waktu Log"
        }, 0);
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbzakat", "root", "");
            St = Con.createStatement();
            Rs = St.executeQuery("SELECT * FROM log_muzaki LIMIT " + posisi + "," + batas);
//             logMustahik.setModel(DbUtils.resultSetToTableModel(Rs));
            while (Rs.next()) {
                int id_log_muzaki = Rs.getInt("id_log_muzaki");
                int id_admin = Rs.getInt("id_admin");
                int id_muzaki = Rs.getInt("id_muzaki");
                String aksi = Rs.getString("aksi");
                String waktu = Rs.getString("waktu");
                model.addRow(new Object[]{
                    id_log_muzaki, id_admin, id_muzaki, aksi, waktu
                });
            }
            jt.setModel(model);

        } catch (Exception e) {
        }
    }

    private void pagiitem() {
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbzakat", "root", "");
            St = Con.createStatement();
            Rs = St.executeQuery("SELECT * FROM log_item");
            Rs.last();
            int jumlah = (int) Math.ceil((Rs.getRow()) / batas) + 1;
            int no = 1;
            paginasiBox2item.removeAllItems();
            while (no <= jumlah) {
                paginasiBox2item.addItem(Integer.toString(no));
                no++;
            }
        } catch (Exception e) {
        }
    }

    private void showLogItem(JTable jt, int posisi) {
        DefaultTableModel model = new DefaultTableModel(new String[]{
            "No Log Item", "ID Admin", "Nama Item", "Jumlah", "Waktu Log"
        }, 0);
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbzakat", "root", "");
            St = Con.createStatement();
            Rs = St.executeQuery("SELECT * FROM log_item LIMIT " + posisi + "," + batas);
//             logMustahik.setModel(DbUtils.resultSetToTableModel(Rs));
            while (Rs.next()) {
                int id_log_item = Rs.getInt("id_log_item");
                int id_admin = Rs.getInt("id_admin");
                String nama_items = Rs.getString("nama_items");
                int jumlah = Rs.getInt("waktu");
                String waktu = Rs.getString("jumlah");
                model.addRow(new Object[]{
                    id_log_item, id_admin, nama_items, jumlah, waktu
                });
            }
            jt.setModel(model);

        } catch (Exception e) {
        }
    }

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel1MouseClicked

    private void AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminMouseClicked
        // TODO add your handling code here:
        JFrame jfAturAdmin = new AturAdmin();
        jfAturAdmin.show();
        dispose();
    }//GEN-LAST:event_AdminMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void printDataExcelLogLoginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printDataExcelLogLoginAdminActionPerformed
        exportExcel(logLogin);
    }//GEN-LAST:event_printDataExcelLogLoginAdminActionPerformed

    private void printDataExcel1MustahikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printDataExcel1MustahikActionPerformed
        exportExcel(logMuzaki);
    }//GEN-LAST:event_printDataExcel1MustahikActionPerformed

    private void printDataExcel2ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printDataExcel2ItemActionPerformed
        exportExcel(logItem);
    }//GEN-LAST:event_printDataExcel2ItemActionPerformed

    private void printDataExcel3MustahikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printDataExcel3MustahikActionPerformed
        exportExcel(logMustahik);
    }//GEN-LAST:event_printDataExcel3MustahikActionPerformed

    private void paginasiBoxloginItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_paginasiBoxloginItemStateChanged
        try {
            int page = Integer.parseInt(paginasiBoxlogin.getSelectedItem().toString());
            int pss = (page - 1) * batas;
            showLogLogin(logLogin, pss);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_paginasiBoxloginItemStateChanged

    private void paginasiBox1mustahikItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_paginasiBox1mustahikItemStateChanged
        // TODO add your handling code here:
        int page = Integer.parseInt(paginasiBox1mustahik.getSelectedItem().toString());
        int pss = (page - 1) * batas;
        showLogMustahik(logMustahik, pss);
    }//GEN-LAST:event_paginasiBox1mustahikItemStateChanged

    private void paginasiBox2itemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_paginasiBox2itemItemStateChanged
        int page = Integer.parseInt(paginasiBox2item.getSelectedItem().toString());
        int pss = (page - 1) * batas;
        showLogItem(logItem, pss);
    }//GEN-LAST:event_paginasiBox2itemItemStateChanged

    private void paginasiBox3muzakiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_paginasiBox3muzakiItemStateChanged
        // TODO add your handling code here:
        int page = Integer.parseInt(paginasiBox3muzaki.getSelectedItem().toString());
        int pss = (page - 1) * batas;
        showLogMuzaki(logMuzaki, pss);
    }//GEN-LAST:event_paginasiBox3muzakiItemStateChanged

    private void paginasiBox1mustahikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paginasiBox1mustahikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paginasiBox1mustahikActionPerformed

    private void paginasiBoxloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paginasiBoxloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paginasiBoxloginActionPerformed

    private void paginasiBox3muzakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paginasiBox3muzakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paginasiBox3muzakiActionPerformed

    private void paginasiBox2itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paginasiBox2itemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paginasiBox2itemActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        JFrame jfIndex = new Index();
        jfIndex.show();
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x= evt.getXOnScreen();
        int y=evt.getYOnScreen();
        setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.setExtendedState(SuperAdmin.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuperAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuperAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuperAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuperAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        if (Muzaki.IdAdminMuzaki.getText().isEmpty()) {
            JFrame login = new Login();
            login.show();
        } else {
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                
                public void run() {
                        new SuperAdmin().setVisible(true);
                }
                
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable logItem;
    private javax.swing.JTable logLogin;
    private javax.swing.JTable logMustahik;
    private javax.swing.JTable logMuzaki;
    private javax.swing.JLabel logout;
    private javax.swing.JTextField namaAdminIndex;
    private javax.swing.JComboBox<String> paginasiBox1mustahik;
    private javax.swing.JComboBox<String> paginasiBox2item;
    private javax.swing.JComboBox<String> paginasiBox3muzaki;
    private javax.swing.JComboBox<String> paginasiBoxlogin;
    private javax.swing.JButton printDataExcel1Mustahik;
    private javax.swing.JButton printDataExcel2Item;
    private javax.swing.JButton printDataExcel3Mustahik;
    private javax.swing.JButton printDataExcelLogLoginAdmin;
    private static javax.swing.JTextField roleAdmin;
    // End of variables declaration//GEN-END:variables
}
